[package]
name = "bevy_chime"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.1" } # default-features = false
impl_op = { path = "../impl_op" }
chime = { path = "../chime" }
accurate = "0.3.1"

[target.'cfg(windows)'.dependencies.bevy]
version = "0.12.0"
features = ["dynamic_linking"]

[profile.dev.package."*"]
opt-level = 3 # Faster dependency compilation

[lib]
name = "bevy_chime"
path = "src/lib.rs"

[[bin]]
name = "testing"
path = "src/bin/testing.rs"